docs(components): Convert docs files
GetJobber/atlantis pull request #1055
Opened 2023-02-21 22:32 UTC by taylorvnoj

## Motivations

## Changes

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2023-02-22 20:25 UTC, MichaelParadis commented on docs/getting-started-with-react/getting-started-with-react.stories.mdx
> +export function ComposingComponents() {
Could this be an example with hooks?

2023-02-22 20:30 UTC, MichaelParadis requested changes
Minor comment. Let me know if you have any questions

2023-02-22 21:57 UTC, taylorvnoj commented on docs/getting-started-with-react/getting-started-with-react.stories.mdx
> +export function ComposingComponents() {
Yes it can! Good catch - thank you!

2023-02-23 15:17 UTC, MichaelParadis approved these changes
LGTM!

2023-02-23 15:18 UTC, merged