feat(components): Only GridCell' s to only be usable in Grids
GetJobber/atlantis pull request #1254
Opened 2023-05-15 16:09 UTC by MichaelParadis

## Motivations

## Changes

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2023-05-15 20:09 UTC, darryltec commented
Oooh, that's a cool approach. What happens when you do it like so?

```html
<Grid>
  <Grid.cell>
    <Grid.cell> </Grid.cell>
  </Grid.cell>
<Grid>
```

would it accept it and not throw an error?

2023-05-15 21:43 UTC, JeffMarvin commented
@MichaelParadis Is there any functional difference/benefit to using this approach vs. the `Chip.tsx` with `useAssert` hook that we have used in the Chips component? (https://github.com/GetJobber/atlantis/blob/master/packages/components/src/Chips/Chip.tsx)

I find that approach a bit more understandable on the surface, so I'm curious what we gain with this approach. :)

2023-05-16 14:26 UTC, MichaelParadis commented
@darryltec @JeffMarvin Updated to use the Chips style of handling it

2023-05-16 19:46 UTC, darryltec requested changes
1 very minor oops

2023-05-16 19:46 UTC, darryltec commented on packages/components/src/Grid/GridCell.tsx
> +  // Throw error when <Chip /> gets used outside of the <Chips />
Oopsies 

```suggestion
  // Throw error when <Grid.Cell /> gets used outside of the <Grid />
```

2023-05-16 19:46 UTC, darryltec commented on packages/components/src/Grid/Grid.tsx
> +        return <InternalGridCell {...gridCell.props} />;
nit

```suggestion
      {React.Children.map(children, { props } => {
        return <InternalGridCell {...props} />;
```

2023-05-17 15:14 UTC, darryltec approved these changes
:shipit:

2023-05-17 15:14 UTC, darryltec commented on packages/components/src/Grid/GridCell.tsx
> +export function GridCell(props: PropsWithChildren<GridCellProps>) {
underscore did not work for this eh?

```suggestion
export function GridCell(_: Props>) {
```

2023-05-17 15:30 UTC, merged