fix(components): Fix input group spacing issues
GetJobber/atlantis pull request #1467
Opened 2023-08-03 14:36 UTC by dlrussel

## Motivations

Due to the fact that FormField wrapper was using a fragment when a form field had a description or a validation message these we being inputted into the DOM as siblings of the wrapper with no parent element to contain them. 

This caused layout issues when input groups were used with the horizontal variation and description/validation errors were being placed into the flex container as siblings of the Form Field Wrapper and being displayed in a row horizontally. See image below:
![image](https://github.com/GetJobber/atlantis/assets/9436525/0500a90f-f2a7-4276-a407-ba1f49a48d96)

This also created spacing inconsistencies for validations/descriptions when inputs were used inside of a `<Content/>` component vs standalone because the content component styles all direct children with padding and therefore description and validation were also having bottom padding applied to them instead of just the group.

## Changes

To resolve this I have added a div that will act as a container element that can wrap Form Field Wrapper as well as description and validation messages so that these elements can be styled as a group. 
See image below:
![image](https://github.com/GetJobber/atlantis/assets/9436525/3fa71f6b-671d-46be-9a43-a33530c3dd66)

### Fixed

- I also updated the invalid class so that it is position relative so that the z-index issue we were seeing with the invalid border color displays properly.
Before:
![image](https://github.com/GetJobber/atlantis/assets/9436525/453ee17b-cba9-46cb-bfff-8cee4535fe11)

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2023-08-04 18:20 UTC, darryltec requested changes
Code looks good to me. Snapshots were easy to check after turning off whitespace changes.

Did saw a bit of an issue with our inline input pattern tho

Master
![image](https://github.com/GetJobber/atlantis/assets/15986172/a403edd1-8888-41ec-91bc-68ea4f99382a)

This branch
![image](https://github.com/GetJobber/atlantis/assets/15986172/8c1309ce-1086-4800-b0b6-ec9c595f5560)


[codesandbox ](https://codesandbox.io/s/white-tree-kj5fhw?file=/package.json)

_If only we have chromatic. One day!_

2023-08-09 18:34 UTC, dlrussel commented on packages/components/src/FormField/FormField.css
> +  display: inline-block;
yes!

2023-08-09 18:35 UTC, dlrussel commented on packages/components/src/FormField/FormField.css
> +  margin-left: var(--space-base);
ah ok good context I have removed this and we can revisit it later on if we want to!

2023-08-09 19:44 UTC, darryltec approved these changes
Alright! We good!! Also fixed the form issue

This branch
![image](https://github.com/GetJobber/atlantis/assets/15986172/cb3eb55e-6514-481e-8547-2fe7b8905497)

Master
![image](https://github.com/GetJobber/atlantis/assets/15986172/f3c15cf6-f634-474e-8327-cfbdb93aa800)

_Perfecto_

2023-08-10 15:11 UTC, merged