feat(components): Permit using children on RadioOption with label
GetJobber/atlantis pull request #1471
Opened 2023-08-03 21:58 UTC by TJKruitbosch

## Motivations

For upcoming work, we would like to have an RadioGroup that has complex RadioOptions that include a label, description, as well as secondary form elements associated with that option as children. For example, consider a group with _Option A_, _Option B_, and _Option C_ as options, but a user selecting _Option A_ must also select from a series of Chips under it, and a user selecting _Option B_ must fill out an InputNumber field.

<img width="323" alt="Screen Shot 2023-08-03 at 3 50 18 PM" src="https://github.com/GetJobber/atlantis/assets/872151/260bef2a-5884-4bfe-840e-fba5325b097f">

[Figma Prototype Link](https://www.figma.com/proto/vOZ51PFeJdaJTkx2pzfGRU/%5BOLB%5D-Maximum-Drive-Time?page-id=10%3A32789&type=design&node-id=182-80076&viewport=-906%2C-759%2C0.19&t=M4jQkAuf2DgjKQF1-1&scaling=min-zoom&starting-point-node-id=182%3A79936) for internal reviewers

## Changes

### Added

### Changed

- RadioOption now supports providing label, description, and children on the same option.

### Deprecated

### Removed

### Fixed

### Security

## Testing

Modify the storybook story/example "Radio Option with Children" to also output the User's name as a label. 

```diff
           {users.map(user => (
-            <RadioOption value={user.name} key={user.name}>
+            <RadioOption value={user.name} key={user.name} label={user.name}>
               <Avatar initials={user.initials} name={user.name} />
             </RadioOption>
           ))}
```
<img width="150" alt="Screen Shot 2023-08-03 at 3 54 58 PM" src="https://github.com/GetJobber/atlantis/assets/872151/20d80c69-6cfa-4881-99bd-b551ab60428f">

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2023-08-04 12:55 UTC, darryltec commented on packages/components/src/RadioGroup/RadioOption.tsx
Haven't really dove into this file but, I wonder if we can simplify this now and not have restrictions anymore. I think we're more mature with react and a11y that restrictions like this might be more confusing than helpful. The moment you reach for only the `children` prop, you are responsible for what goes in there and are saying "I don't want the default interaction"

What do you think?

2023-08-08 15:07 UTC, TJKruitbosch commented on packages/components/src/RadioGroup/RadioOption.tsx
Taking another look at this with fresh post-weekend eyes...I think the "you must provide _at least one of_ `label` and `children`" restriction still makes sense here. The component itself doesn't make a lot of sense visually without _something_ in the label area. That said, I think the types are a little over-complex for expressing that, and I can give simplifying it a shot.

2023-08-08 16:39 UTC, darryltec commented on packages/components/src/RadioGroup/RadioOption.tsx
Coolio! Thanks homie!

2023-08-08 21:47 UTC, TJKruitbosch commented on packages/components/src/RadioGroup/RadioOption.tsx
I gave refactoring the prop types here a shot. There's now just one type for the "internal" options, just one human-readable type for the external options, and one intermediate type solely for enforcing the "you must provide at least one of label or children" rule. If it turns out in the future that I'm totally wrong here (it happens, no big deal 🤷‍♂️) and that RadioOptions without labels or children should be permitted, it should be straightforward to just remove that intermediate type and use `BaseRadioOptions` directly. What do you think?

2023-08-09 14:01 UTC, darryltec requested changes
Haven't tested this but a few little bits I saw. Thanks for simplifying the types on this!

2023-08-09 16:05 UTC, TJKruitbosch commented on packages/components/src/RadioGroup/RadioOption.tsx
> +      {children && label && (
No strong feelings against that, I just live in constant fear of the max-lines lint rule ruining my day. 

How about `shouldRenderIndependentChildren`?

2023-08-09 16:28 UTC, TJKruitbosch commented on packages/components/src/RadioGroup/RadioOption.tsx
> +type BaseRadioOptions = PropsWithChildren<{
Only thing I disagree with here is that documentation saying more about why not to use this prop and nothing about what it does or why you would use it. Do you mind if I re-frame it to start with what this does and what it's for before getting into using the other props if possible as best practice?

2023-08-09 16:34 UTC, darryltec commented on packages/components/src/RadioGroup/RadioOption.tsx
> +type BaseRadioOptions = PropsWithChildren<{
Sure thing!

The only reason why it went with do not use is children is the most straightforward prop there is and reaching for it is pretty common and known. Compared to a label prop existing. So if you're reaching for children, get them out of there fast if they don't know that label exists. If they do know that label exist, they already know what they want to use it for.

2023-08-10 21:32 UTC, darryltec requested changes
I think this looks pretty good and works!! Gonna trigger a pre-release to make sure we don't hit any typing issues within Jobber. 

While we're waiting, what do you think about the "Radio option with children" being renamed as "Custom Radio Option Content" and update it closer to your screenshot. I believe, that's how it would be used most of the time compared to avatars.

maybe go with

- Fixed time
Select from the 15 mins interval
[ 15 mins ] [ 30 mins ] [ 45 mins ] [ 60 mins ]
- Specific time
Set your reminder down to the minute
Remind me at [ 42 | mins ] and [ 3 | sec ] interval

2023-08-10 21:32 UTC, darryltec commented on packages/components/src/RadioGroup/RadioOption.tsx
> +   * content of either would be text.
I think we can simplify this and get straight to the point.

```suggestion
   * Render a custom label or additional content below the `label`
   * and `description`.
   *
   * Prefer using `label` and `description` over adding child elements if the
   * content of either would be a string.
```

2023-08-11 13:27 UTC, darryltec approved these changes
Loooooks good homie! Thanks for contributing to improve Atlantis! Did not see type issues in Jobber

2023-08-11 13:27 UTC, merged