feat(components): localized date formatter
GetJobber/atlantis pull request #1504
Opened 2023-08-28 19:11 UTC by darryltec

## Motivations

Now that we are starting to support localization, date and time formatters needs to be localized too

## Changes

### Added

- `formatTime` and `formatDate` in the `useAtlantisI18n` hook to automatically localized the date or time string depending on your settings in Atlantis Context

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2023-08-30 18:58 UTC, ZakaryH commented
I'm a bit nervous about the test coverage here

when I run the tests in `useAtlantisI18n.test.ts` along with a `console.log(timeZone)` in the `dateFormatter` method, it's running as `UTC`, meaning that `utcToZonedTime` isn't doing a whole lot with this set of data because it'll be converting a utc time to.... well, utc

I admit that this is borderline testing the functionality of `utcToZonedTime`, and that one reason it could be failing is that there's something wrong with that library's method, or the `date-fns` `format` method which is the other piece we're using here - but I feel like the combination of those two that we are using to achieve the functionality is worth testing

could we please add some tests other timezones and verify the output is correct? 

so one timezone with a negative offset which can be anything in North America (that observes DST, maybe don't choose Phoenix since that could get weird.... or maybe do? idk)

then another timezone with a positive offset, so maybe something in Asia or Australia.

thinking about how to do this, you'd probably want to use `timezone-mock` because by default in Jest, the timezone returned whenever you ask the machine for its tz, it'll be UTC like what we're probably seeing in these tests

https://github.com/Jimbly/timezone-mock

hopefully that's chill to add a dev dependency here, but if not just lmk!

2023-08-30 18:59 UTC, ZakaryH requested changes
would love to have some more test coverage when timezones are not UTC

left a comment with some thoughts, happy to chat about it!

2023-08-30 19:23 UTC, darryltec commented
@ZakaryH oh good! was thinking of testing another time zone after our chat on Monday so yeah, will look into that bad boi

2023-08-30 20:46 UTC, darryltec commented on packages/components-native/src/hooks/useAtlantisI18n/useAtlantisI18n.ts
>    readonly t: (
That's a common pattern.

https://www.i18next.com/overview/api#t
https://guides.rubyonrails.org/i18n.html#the-public-i18n-api

2023-08-30 20:46 UTC, MichaelParadis commented on packages/components-native/src/hooks/useAtlantisI18n/useAtlantisI18n.ts
>    readonly t: (
@darryltec thanks for the context. I don't like it but that is a me thing.

2023-08-31 00:58 UTC, ZakaryH approved these changes
awesome, thanks for adding those tests!

LGTM

2023-08-31 12:56 UTC, merged