feat(components): Add DataList.Banner
GetJobber/atlantis pull request #1596
Opened 2023-10-19 13:55 UTC by rodrigoeidelvein

## Motivations

## Changes

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2023-10-19 20:51 UTC, darryltec commented on docs/components/DataList/DataList.stories.mdx
> +Atlantis
```suggestion
inform the user about something related to the Datalist. It renders an
Atlantis
```

2023-10-19 20:52 UTC, darryltec commented on docs/components/DataList/DataList.stories.mdx
> +component
```suggestion
component.
```

2023-10-19 21:28 UTC, chris-at-jobber commented
I'm not sure I'm sold on the naming of this subcomponent as "DataList Banner". It feels 
a bit too declarative (if we decided to present errors in a different format than Banner, this breaks), and the documentation is basically just describing the Banner component.

If we want to be more specific about _current_ usage, something like DataList Error State would be more helpful, and if we want to be a bit more general about other possible usages, something like DataList Status (DataList StatusMessage?) could be more flexible.

2023-10-20 15:36 UTC, rodrigoeidelvein commented
@chris-at-jobber Yeah, I didn't want to keep it just for errors because it might be useful for other usages like giving tips, warnings, and notices... it seems to me that it could be useful other than just being an error banner.

`BannerMessage`, maybe? 🤔

2023-10-20 15:42 UTC, chris-at-jobber commented
I'd leave Banner out of it as that's really coupled to the specific current implementation. If we decided to use a StatusLabel or maybe just some red text to indicate the same information, the name would be really confusing, where if we just leave it as "DataList Message or "DataList Status Message" it's more flexible.

2023-10-20 15:50 UTC, rodrigoeidelvein commented
@chris-at-jobber okay, I have an idea. What about calling it "StatusBar" (props to Darryl for this name), and then we reserve that space to "status" things, it could be a Banner, a StatusLabel, or however the consumer wants to provide a status there and render its children.

Something like this:
```tsx
<DataList.StatusBar>
  <Banner type="error">message here</Banner>
</DataList.StatusBar>
```

2023-10-20 16:07 UTC, chris-at-jobber commented
Nice! I like that

2023-10-24 19:16 UTC, darryltec requested changes
just a few little things

2023-10-24 19:16 UTC, darryltec commented on packages/components/src/DataList/DataList.tsx
> + * Defines a banner that is going to rendered between the filters and the header.
```suggestion
 * Defines a banner that is going to be rendered between the filters and the header.
```

2023-10-24 19:16 UTC, darryltec commented on packages/components/src/DataList/components/DataListStatusBar/DataListStatusBar.tsx
> +  return <>{children && children}</>;
```suggestion
  const children = component.props.children;

  return <>{children}</>;
```

should suffice

2023-10-24 19:23 UTC, chris-at-jobber commented on packages/components/src/DataList/DataList.tsx
> + * Defines a banner that is going to rendered between the filters and the header.
```suggestion
 * Defines a banner that is rendered between the filters and the header.
```

Even shorter

2023-10-24 19:24 UTC, darryltec commented on packages/components/src/DataList/DataList.tsx
> + * Defines a banner that is going to rendered between the filters and the header.
even better

2023-10-24 19:28 UTC, chris-at-jobber commented on docs/components/DataList/DataList.stories.mdx
> +### Status Bar
```suggestion
### Status bar
```

Sentence case per our[ guidelines](https://job-80005-add-datalist-banne.atlantis.pages.dev/?path=/docs/content-formatting--page#capitalization)

2023-10-24 19:28 UTC, chris-at-jobber commented
The screenshot looks good and I'm happy with the naming - I don't want to block the PR on this but it would be great to have a story added, as since it's not a prop it's hard to see otherwise.

2023-10-24 19:31 UTC, rodrigoeidelvein commented on packages/components/src/Banner/Banner.tsx
Nope! Reverting it

2023-10-24 20:10 UTC, darryltec commented on packages/components/src/Banner/index.ts
> +export { Banner, BannerType, BannerProps } from "./Banner";
```suggestion
export { Banner, BannerType } from "./Banner";
```

this is the error

2023-10-24 20:11 UTC, rodrigoeidelvein commented on packages/components/src/Banner/index.ts
> +export { Banner, BannerType, BannerProps } from "./Banner";
Yeah, I was just pushing a commit 🤦

2023-10-24 20:29 UTC, darryltec approved these changes
ship it!

2023-10-24 20:29 UTC, merged