fix(components): static thumbnails for HEIC in all browsers but safari (fixes forever loading thumbnail for HEIC) [84773]
GetJobber/atlantis pull request #1712
Opened 2024-01-08 23:47 UTC by tyler-santos

## Motivations

## Changes

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2024-01-09 20:09 UTC, ZakaryH commented
regarding the package vs MDN code snippet question, let's err on the side of avoiding packages when possible! while that code is a bit verbose due to having to go over each case in that order, I think it's still preferable to adding an entire package

this is because the package has more things we might not need but also because....

**Remix + making it safe for the server**

something we're going to be working on very soon is making our code safe for Remix's server side rendering

when rendering on the server, we won't have a browser/window/document to talk to which means we have to add guards around anything trying to access something like `window.navigator.userAgent` so that it won't have a bad time

all that is to say let's do the following
- use the MDN snippet
- let's add a util file in `packages/components/src/utils` 
- add a modification that will first check for `typeof document === "undefined"` before we try to access `navigator.userAgent` and let it fallback to the default on the server, when it renders on the client it'll get the right answer
- https://remix.run/docs/en/main/guides/gotchas#typeof-window-checks

2024-01-09 20:09 UTC, ZakaryH commented
>Updates the basic icon for images to be image instead of camera

do you happen to have a screenshot of this change? I'm going to try to get it myself in the meantime, but if you have it handy it'd be nice to document on the PR

2024-01-09 20:11 UTC, ZakaryH requested changes
let's go with the MDN snippet + the Remix guards please and thank you

once we're on that I can give this a QA pass

also appreciate the tests!

2024-01-10 23:10 UTC, tyler-santos commented
@ZakaryH Thanks so much for reviewing this! I think I have addressed all of the feedback and created some extra utilities to get this to behave similarly to that library (functions for isSafari, isChrome, etc).

2024-01-11 19:15 UTC, ZakaryH commented
tried a few uploads on Chrome
- jpg
- svg
- HEIC

![image](https://github.com/GetJobber/atlantis/assets/11843215/a8e8d5d0-93f4-4c85-b93d-abfdb095ad77)

even though my file was `blah.HEIC` it was still correctly identified so good to know it's not case sensitive

also the thumbnail is correctly showing as the image icon rather than camera

then on Safari

![image](https://github.com/GetJobber/atlantis/assets/11843215/6659146b-1327-4617-bf43-63db677b99e4)

HEIC thumbnail showing as intended

interesting that I am allowed to upload HEIC files in Safari without modifying the selection dialog options like I had to do in Chrome to upload that HEIC

Firefox

![image](https://github.com/GetJobber/atlantis/assets/11843215/972fffc3-8317-4ec8-ac05-0e0bfa51c20f)

and Edge
![image](https://github.com/GetJobber/atlantis/assets/11843215/74f04fde-d4fc-41c8-b0e2-2d781a074a1b)

2024-01-11 19:23 UTC, ZakaryH commented
tried making the `userAgent` undefined/empty string and that correctly falls back to the default! 🎉

![image](https://github.com/GetJobber/atlantis/assets/11843215/ec2382db-11d1-4d4c-8100-887953ec9b5a)

2024-01-11 20:41 UTC, chris-at-jobber reviewed
Design approved on the icon change, makes more sense tbh

2024-01-11 20:41 UTC, ZakaryH approved these changes
LGTM

2024-01-11 20:42 UTC, merged