docs(design): update swatches and fix broken base colors
GetJobber/atlantis pull request #1999
Opened 2024-08-27 23:36 UTC by chris-at-jobber

## Motivations

Base color palette was rendering extremely incorrectly
![image](https://github.com/user-attachments/assets/f6cd3493-ba7b-4d03-a860-47a754566da7)

## Changes

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

Changes can be
[tested via Pre-release](https://github.com/GetJobber/atlantis/actions/workflows/trigger-qa-build.yml)

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2024-08-28 12:06 UTC, scotttjob commented
There's definitely an opportunity to not have to define the tokens you want to display manually. There's probably even an opportunity to create this specific grouping in the generated token files, and we keep that knowledge in the token package. Let's chat!

2024-08-28 16:14 UTC, chris-at-jobber commented on .storybook/assets/css/preview.css
> +  outline: transparent;
enables outlines for users in high-contrast mode

2024-08-28 16:15 UTC, chris-at-jobber commented on .storybook/assets/css/preview.css
> +:global(a) {
linter was unhappy with the un-scoped styles here (a rule which we rightly added to prevent components styles from "leaking")

2024-08-28 16:15 UTC, chris-at-jobber commented on .storybook/assets/css/preview.css
> +:global(.sb-show-main code) {
code snippets were not responding to dark mode

2024-08-28 16:16 UTC, chris-at-jobber commented on .storybook/components/ColorSwatches/ColorSwatches.module.css
> +  --swatchSize: 64px;
[Size  ≠ space](https://atlantis.getjobber.com/?path=/docs/guides-frontend-styleguide--docs#size-width-and-height)

2024-08-28 16:18 UTC, chris-at-jobber commented on .storybook/components/ColorSwatches/ColorSwatches.tsx
> +      <Content spacing="small">
removing a bunch of custom styling by using Atlantis layout components

2024-08-28 16:19 UTC, chris-at-jobber commented on .storybook/components/ColorSwatches/ColorSwatches.tsx
> +        { description && (<Text>{description}</Text>) }
This slot and prop will allow us to pass in the description of each token from the json file once added

2024-08-28 16:19 UTC, chris-at-jobber commented on .storybook/components/ColorSwatches/ColorSwatches.tsx
> +            <Button size="small" variation="subtle" type="tertiary" icon="copy" onClick={handleClick} ariaLabel="Copy" />
Moving the button out of the swatch itself

2024-08-28 16:20 UTC, chris-at-jobber commented on .storybook/components/ColorSwatches/ColorSwatches.tsx
> +      <Content spacing="small">
![image](https://github.com/user-attachments/assets/a1477894-c57e-4984-b3b3-269265d5453e)

2024-08-28 16:22 UTC, chris-at-jobber commented on docs/design/Colors.stories.mdx
> -<ColorSwatches colors={colors} />
This fixes the "undefined" and unexpected groupings. It's less elegant than automatically pulling all values, but
- it works
- it did not take me very long
- we don't frequently update the base palette 

So I am advocating that if an engineer is interested, they tackle this in a followup

![image](https://github.com/user-attachments/assets/c560dfa9-4dfc-4787-babc-15df3216f84d)

2024-09-03 19:33 UTC, nad182 requested changes
I'm not sure about this, but it looks like the `Borders` section might be incorrect:
#### Before
<img width="1391" alt="image" src="https://github.com/user-attachments/assets/c97c22aa-39bb-4cb4-9dd3-c1e8d4ce984f">

#### After
<img width="1340" alt="image" src="https://github.com/user-attachments/assets/c448f297-970e-4500-8fb4-80f646c6663b">

2024-09-03 19:37 UTC, chris-at-jobber commented
@nad182 that's intended, instead of doing (kind of arbitrary) different treatments for borders, I'm just treating them as swatches now

2024-09-03 20:23 UTC, nad182 approved these changes
Considering, it was decided not to pull colour/token values in this PR, code looks good.

One (optional) suggestion is to hide the list of "Base colors" in the collapsible `<details>`:
<img width="823" alt="image" src="https://github.com/user-attachments/assets/e07e8314-9d3b-49ea-a176-e0fd00973647">
<img width="863" alt="image" src="https://github.com/user-attachments/assets/76962b9c-08a2-48f3-9218-a322b1522e51">


```jsx
<details>
  <summary>This is the underlying color palette that powers our semantic system. Direct use of these colors should be avoided, as they do not respond to theming or systemic changes.</summary>
  <Swatch
    colors={[
      "--color-base-taupe--100",
      ...,
    ]}
  />
</details>
```

This would sort of hide from view the list of tokens that shouldn't be referenced directly. However, they still would be available for references.

Nevertheless, I'm good to approve this PR as is!

2024-09-03 21:16 UTC, chris-at-jobber commented
@nad182 good idea! I'm going to try that in a branch off of this one, maybe try using our own Disclosure and see how that goes 😄

2024-09-03 21:17 UTC, merged

2024-09-03 22:07 UTC, chris-at-jobber commented
https://github.com/GetJobber/atlantis/pull/2008