fix(components): Hide row actions on hover and right click in multiselect mode
GetJobber/atlantis pull request #2012
Opened 2024-09-04 16:47 UTC by nad182

## Motivations

## Changes

### Added

- Added conditions to `shouldShowContextMenu` and `shouldShowHoverMenu` to hide the context and hover menus in case at least one of the items in `DataList` is selected.

### Changed

- Changed the type of `selected` property in DataList, since it should be a list (array) of "id"(s)

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

Changes can be
[tested via Pre-release](https://github.com/GetJobber/atlantis/actions/workflows/trigger-qa-build.yml)

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2024-09-04 22:35 UTC, chris-at-jobber reviewed
Design approved ✅ 

Interaction-wise this is as expected - there are no more "item-specific" actions available either on right click or on hover when in multi-select mode.

2024-09-10 20:44 UTC, MichaelParadis requested changes
Minor changes to a test (the menu wouldn't show because there were no visible actions)

2024-09-10 20:44 UTC, MichaelParadis commented on packages/components/src/DataList/components/DataListItem/DataListItem.test.tsx
> +          <DataListAction label="Edit" visible={() => false} />
The menu would never show up even if selected because the actions aren't visible. 
```suggestion
          <DataListAction label="Edit" />
```

2024-09-10 20:44 UTC, MichaelParadis commented on packages/components/src/DataList/components/DataListItem/DataListItem.test.tsx
> +          <DataListAction label="Email" visible={() => false} />
```suggestion
          <DataListAction label="Email" />
```
Same as above

2024-10-08 15:56 UTC, MichaelParadis commented
Closing this for now. There were a bunch of edgecases we didn't consider and we may look at this in the future

2024-10-08 15:56 UTC, closed without merging