chore(design): Added descriptions to semantic tokens JSON files
GetJobber/atlantis pull request #2107
Opened 2024-11-05 20:18 UTC by edison-cy-yang

## Motivations

This is an enabler so we can use semantic descriptions in docs

## Changes

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

Changes can be
[tested via Pre-release](https://github.com/GetJobber/atlantis/actions/workflows/trigger-qa-build.yml)

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2024-11-05 20:26 UTC, edison-cy-yang commented
@chris-at-jobber A couple of questions that I came across while adding these descriptions:

- should some of the tokens json structures be changed, eg dont make `subtle` on the same level as `hover` in `interactive-` of `semanticColor.tokens.json`?

- semantic colors for workflows in light mode are set in `workflow.tokens.json` but the ones for dark mode are set in `dark.tokens.json`. Should we make the locations of these tokens consistent?

- Should the same description be applied to the hover, surface, and onSurface states of a semantic color?

2024-11-06 00:18 UTC, chris-at-jobber commented
@edison-cy-yang 

### Token structure
If that would change the output values then I would say no, as that would be a massive breaking change, but if it's not, then maybe? I'm not sure what exactly that change would look like.

### Workflow colors
I would be OK with moving the token definitions from `workflow.tokens` into `semanticColor.tokens`, I'm not sure if that would have any knock-on effects (@scotttjob might know!)

### Description for hover/etc 
Couldn't hurt! I think as a general rule for 
- hover tokens
  - "Hover state for {the token it's referencing}"
- surface/onSurface tokens
  - "Use for the surface of an element that has {status it's referencing} status"
  - "Use for text or iconography that sits overtop a {same status surface value} background"

2024-11-06 12:06 UTC, scotttjob commented
> If that would change the output values then I would say no, as that would be a massive breaking change, but if it's not, then maybe? I'm not sure what exactly that change would look like.

Changing the structure of the JSON would definitely change the final token value. (each 'level' traversed in the JSON file is translated to a dash in the final token)

> I would be OK with moving the token definitions from `workflow.tokens` into `semanticColor.tokens`, I'm not sure if that would have any knock-on effects (@scotttjob might know!)

The only concern I have is for the token aliases, I believe they'll still be processed properly but would want to verify that.

Ideally the only thing that would change from this would be potentially the tokens appearing in a different order in the generated output, but the contents would be identical. So I would be comfortable with this update if I could see that Diff as part of the PR.

2024-11-06 19:51 UTC, edison-cy-yang commented
@chris-at-jobber @scotttjob Thanks! I will leave those structural JSON changes out for now. I want to take a look at parsing token descriptions next, hoping I will have more understanding and feel more comfortable making these by then.

Descriptions for hover, surface, and onSurface states added.

2024-11-07 00:28 UTC, chris-at-jobber requested changes
Looks great! Couple of suggestions to be less descriptive about "white" or "dark" surfaces as the lightness or darkness changes per theme/mode

2024-11-07 00:28 UTC, chris-at-jobber commented on packages/design/src/tokens/dark.tokens.json
> +            "$description": "Headings have a bold, dark color to cement their hierarchy."
```suggestion
            "$description": "Headings have high contrast against the application surface to cement their hierarchy."
```

This is an oversight on my part on the content side, just going to make a few of these suggestions where we're referencing "dark" or "light" directly in the semantic tokens to be more _semantic_ and less _descriptive_. (I'll make these changes in the Figma as well!)

2024-11-07 00:28 UTC, chris-at-jobber commented on packages/design/src/tokens/dark.tokens.json
> +                "$description": "Use on “reversed” (light) sections."
```suggestion
                "$description": "Use for typographic content against reversed (inverted theme) surfaces."
```

2024-11-07 00:28 UTC, chris-at-jobber commented on packages/design/src/tokens/dark.tokens.json
> +                    "$description": "Secondary text for “reversed” sections."
```suggestion
                    "$description": "Secondary text color for use against reversed (inverted theme) surfaces."
```

2024-11-07 00:28 UTC, chris-at-jobber commented on packages/design/src/tokens/dark.tokens.json
> +            "$description": "Most elements in Jobber have a white surface; if clickable, they have a light hover and active color."
```suggestion
            "$description": "The primary color of the application surface (background). If interactive, surfaces have a hover and active color."
```

2024-11-07 00:28 UTC, chris-at-jobber commented on packages/design/src/tokens/dark.tokens.json
> +                "$description": "When a strong constrast is needed with the rest of the application, a reversed surface can be used."
```suggestion
                "$description": "Use a reverse surface to invert the theme when a strong contrast is needed with the rest of the application"
```

2024-11-07 00:28 UTC, chris-at-jobber commented on packages/design/src/tokens/semanticColor.tokens.json
> +      "$description": "Headings have a bold, dark color to cement their hierarchy."
```suggestion
      "$description": "Headings have a high contrast against the application surface to cement their hierarchy."
```

2024-11-07 00:28 UTC, chris-at-jobber commented on packages/design/src/tokens/semanticColor.tokens.json
> +        "$description": "Use on “reversed” (dark) sections."
```suggestion
        "$description": "Use for typographic content against reversed (inverted theme) surfaces."
```

2024-11-07 00:28 UTC, chris-at-jobber commented on packages/design/src/tokens/semanticColor.tokens.json
> +          "$description": "Secondary text for “reversed” sections."
```suggestion
          "$description": "Secondary text for use against reversed (inverted theme) surfaces."
```

2024-11-07 00:28 UTC, chris-at-jobber commented on packages/design/src/tokens/semanticColor.tokens.json
> +      "$description": "Most elements in Jobber have a white surface; if clickable, they have a light hover and active color."
```suggestion
      "$description": "The primary color of the application surface (background). If interactive, surfaces have a hover and active color."
```

2024-11-07 00:28 UTC, chris-at-jobber commented on packages/design/src/tokens/semanticColor.tokens.json
> +        "$description": "When a strong constrast is needed with the rest of the application, a reversed surface can be used."
```suggestion
        "$description": "Use a reverse surface to invert the theme when a strong contrast is needed with the rest of the application."
```

2024-11-07 17:22 UTC, scotttjob reviewed
I ran through these quickly, did not run the code directly.

Can we run a quick diff on the output of the generated files before and after this change? There should be no change.

I normally wouldn't ask for a diff, but there's enough changes in here that a diff is a good sanity check.

2024-11-07 17:46 UTC, edison-cy-yang commented
> I ran through these quickly, did not run the code directly.
> 
> Can we run a quick diff on the output of the generated files before and after this change? There should be no change.
> 
> I normally wouldn't ask for a diff, but there's enough changes in here that a diff is a good sanity check.

@scotttjob those generated css and js files are gitignored, by seeing the diff are you talking about temporarily adding those files to the index and running diff on them (then removing them from index)?

In this case would it make sense to include this step (in a shell script) as part of running `npm run bootstrap` just to confirm the diffs are what we expected?

2024-11-07 18:01 UTC, scotttjob commented
> > I ran through these quickly, did not run the code directly.
> > Can we run a quick diff on the output of the generated files before and after this change? There should be no change.
> > I normally wouldn't ask for a diff, but there's enough changes in here that a diff is a good sanity check.
> 
> @scotttjob those generated css and js files are gitignored, by seeing the diff are you talking about temporarily adding those files to the index and running diff on them (then removing them from index)?
> 
> In this case would it make sense to include this step (in a shell script) as part of running `npm run bootstrap` just to confirm the diffs are what we expected?

I don't think we have to go that far, I was thinking just a manual diff. So if you swapped branches back to master, ran the build command, copied the files out, swapped branches, ran the command again, then manually compared.

So a one-off screenshot. :)

2024-11-07 18:43 UTC, edison-cy-yang commented
> > > I ran through these quickly, did not run the code directly.
> > > Can we run a quick diff on the output of the generated files before and after this change? There should be no change.
> > > I normally wouldn't ask for a diff, but there's enough changes in here that a diff is a good sanity check.
> > 
> > 
> > @scotttjob those generated css and js files are gitignored, by seeing the diff are you talking about temporarily adding those files to the index and running diff on them (then removing them from index)?
> > In this case would it make sense to include this step (in a shell script) as part of running `npm run bootstrap` just to confirm the diffs are what we expected?
> 
> I don't think we have to go that far, I was thinking just a manual diff. So if you swapped branches back to master, ran the build command, copied the files out, swapped branches, ran the command again, then manually compared.
> 
> So a one-off screenshot. :)

Picked a few files

![Screenshot 2024-11-07 at 10 40 59 AM](https://github.com/user-attachments/assets/6b4f535c-d21e-45a1-8d28-4873d5d3124e)
![Screenshot 2024-11-07 at 10 41 16 AM](https://github.com/user-attachments/assets/7a3a2530-b086-4c6b-93ed-014d372a716a)
![Screenshot 2024-11-07 at 10 41 47 AM](https://github.com/user-attachments/assets/a13a97d5-f78b-4f2d-815d-e27f8f2968db)

2024-11-07 18:55 UTC, scotttjob commented
> > > > I ran through these quickly, did not run the code directly.
> > > > Can we run a quick diff on the output of the generated files before and after this change? There should be no change.
> > > > I normally wouldn't ask for a diff, but there's enough changes in here that a diff is a good sanity check.
> > > 
> > > 
> > > @scotttjob those generated css and js files are gitignored, by seeing the diff are you talking about temporarily adding those files to the index and running diff on them (then removing them from index)?
> > > In this case would it make sense to include this step (in a shell script) as part of running `npm run bootstrap` just to confirm the diffs are what we expected?
> > 
> > 
> > I don't think we have to go that far, I was thinking just a manual diff. So if you swapped branches back to master, ran the build command, copied the files out, swapped branches, ran the command again, then manually compared.
> > So a one-off screenshot. :)
> 
> Picked a few files
> 
> ![Screenshot 2024-11-07 at 10 40 59 AM](https://private-user-images.githubusercontent.com/13080143/384096807-6b4f535c-d21e-45a1-8d28-4873d5d3124e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMDU5NTcsIm5iZiI6MTczMTAwNTY1NywicGF0aCI6Ii8xMzA4MDE0My8zODQwOTY4MDctNmI0ZjUzNWMtZDIxZS00NWExLThkMjgtNDg3M2Q1ZDMxMjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE4NTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNGU2OWFjOWQ5YjRhZmUyNWMxZTlhMTY2M2YzNGQzZTYyOGRhM2IzZTc4MmQ2MTBlMWQxMTQ4MTZhZDUwNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7DqEiSgzRx7rwO1JjdHbYUv5-PuHUkqRDtq4S6qBjeQ) ![Screenshot 2024-11-07 at 10 41 16 AM](https://private-user-images.githubusercontent.com/13080143/384096815-7a3a2530-b086-4c6b-93ed-014d372a716a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMDU5NTcsIm5iZiI6MTczMTAwNTY1NywicGF0aCI6Ii8xMzA4MDE0My8zODQwOTY4MTUtN2EzYTI1MzAtYjA4Ni00YzZiLTkzZWQtMDE0ZDM3MmE3MTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE4NTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNGUwZGQwMWU4N2U3YTM0OWJjYjY0MjY1NWQ0ZTZhZTFmMGMyMDU2MzM0NTYwZGI4M2I5OGU4NTBjODU3NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cukOWOAw42ClUr5prNRbktOqwzJSvY6PeBV55YJIRcQ) ![Screenshot 2024-11-07 at 10 41 47 AM](https://private-user-images.githubusercontent.com/13080143/384096820-a13a97d5-f78b-4f2d-815d-e27f8f2968db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMDU5NTcsIm5iZiI6MTczMTAwNTY1NywicGF0aCI6Ii8xMzA4MDE0My8zODQwOTY4MjAtYTEzYTk3ZDUtZjc4Yi00ZjJkLTgxNWQtZTI3ZjhmMjk2OGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE4NTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4N2RlZmZmYjBkZmVkZmZlODdkNjBmNGFlY2I1NjAzNjBiY2MyZTAzZDA5ODA2NzVlYTFlNjA1NjM1NDc3ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4R-0SV_gaueFLnl2LAhZpPzdeNZEGQcag5nSMorEf6w)

Amaaaaaaazing! That's exactly the kind the reassurance I was looking for. Great work Edi!

2024-11-07 19:03 UTC, chris-at-jobber approved these changes
Looks great! Thanks @edison-cy-yang

2024-11-07 21:49 UTC, merged