docs: Add Not Found Page [JOB-111818]
GetJobber/atlantis pull request #2274
Opened 2024-12-20 22:46 UTC by Aiden-Brine

I am opening this PR because @Beccaneer  is gone for the holidays but full credit for this lovely 404 page goes to her. I just did some routing touch ups at the end.

### Added

A new 404 page when a page isn't found on the docs site.

### Additional context
Here is an explanation of the routing changes I made.

https://github.com/user-attachments/assets/653d6f81-2455-493d-8d56-3737a413b445

## Testing

Make sure all the routing is working as expected. Make sure the 404 page is rendering when you hit an endpoint that doesn't exist.

Changes can be
[tested via Pre-release](https://github.com/GetJobber/atlantis/actions/workflows/trigger-qa-build.yml)

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2025-01-06 13:09 UTC, scotttjob requested changes
I'd love for us to revisit the useEffect + timeout solution, that's a bit of a code smell to me. If there's a specific reason for it, that's okay, but I'd like us to document that specific reason + why another solution didn't work (just as a JSDoc comment above the bit of code).

Also I'd like to get the NodeJS.Timeout type out, it doesn't belong.

Otherwise my comments are just comments, and I'll be able to approve after we sort out those two small issues.

2025-01-06 13:09 UTC, scotttjob commented on packages/site/src/routes.tsx
> +import { ComponentNotFound } from "./components/ComponentNotFound";
This content was created for us to help us understand why a component wasn't showing up after we transferred it into the system.

So while I appreciate us keeping the content as a specific route, I don't think everyone will ever visit it directly (since before this it was acting as a 404 page).

Would it make sense to move this content into a new "Working with the Docs site" section of our docs?

2025-01-06 13:09 UTC, scotttjob commented on packages/site/src/pages/NotFoundPage.tsx
> +  useEffect(() => {
This is a smell to me, with the useEffect and two timeouts + tracking one of them for clearing it. I know this is just a 404 page, so really low-risk overall, but what is this useEffect accomplishing? I see the comment below with the setTimeout and 0 as the delay, in that case however a `requestAnimationFrame` would be the better solution, as the code will be called on the next tick like you're wanting.

Is the idea to select a random fish to display?

2025-01-06 13:09 UTC, scotttjob commented on packages/site/src/pages/NotFoundPage.tsx
> +  const timeoutRef = useRef<NodeJS.Timeout | null>(null);
This is the wrong type. It's not a NodeJS Timeout, but just a Number. The NodeJS Timeout would be true if this was running on the server.

2025-01-06 13:14 UTC, Beccaneer commented on packages/site/src/pages/NotFoundPage.tsx
> +  useEffect(() => {
This is my newness to React showing through a bit :) I will give that a try!

2025-01-06 13:15 UTC, Beccaneer commented on packages/site/src/routes.tsx
> +import { ComponentNotFound } from "./components/ComponentNotFound";
@taylorvnoj  mentioned concerns about not having this content included in some way

2025-01-06 13:16 UTC, Beccaneer commented on packages/site/src/pages/NotFoundPage.module.css
> +        --R: calc(var(--size)*1.28);
Not generated! I frankensteined this together a bit from various open sources code pieces, I will give that a look!

2025-01-07 16:38 UTC, chris-at-jobber commented
A few suggestions:

- It would be nice to get the text content center-aligned
- should use our `Heading level={"1"}` for the h1
- I think it could be helpful to give an explicit "go home" action to give the user an explicit remediation
- Also tried some ideas for simplifying the copy a bit while still keeping the fun nautical vibes 

![image](https://github.com/user-attachments/assets/a1cd9d59-b364-4572-a602-f0524bf8b4e7)
![image](https://github.com/user-attachments/assets/949414cc-423e-414b-a982-904b958d3ee5)
![image](https://github.com/user-attachments/assets/fa7ad14c-4c0f-4483-bc2d-c88108c9b2be)

2025-01-07 17:00 UTC, taylorvnoj commented on packages/site/src/routes.tsx
> +import { ComponentNotFound } from "./components/ComponentNotFound";
@scotttjob I think that content might still be valuable to keep as a link on the 404 pages for any component not found path, because it will give good hints to future devs as to why a new component might not be showing up on the site.
I'm gonna play devils advocate and say, no one will seek out a different page in our docs to figure out why they're running into issues. It's likely in both cases they'll come ask us. 
I'm of the thought that a link is the most intuitive - unless we put that info on the 404 page itself when a component isn't found, if we want to avoid creating another route.

2025-01-08 13:55 UTC, scotttjob approved these changes
Changes look good to me on the code front! Appreciated.

Chris left some design feedback, but we might be able to corral that into a new ticket and address it soon after the soft launch?

2025-01-08 13:55 UTC, scotttjob commented on packages/site/src/routes.tsx
> +import { ComponentNotFound } from "./components/ComponentNotFound";
Great use of devil's advocate Taylor, I completely agree. I'll sheepishly admit I didn't notice the bit of copy referencing the page and directing us there, so I thought it had become disconnected.

Really actually like this solution of keeping it a link with information, so great work all around.

2025-01-08 19:48 UTC, merged