drawer-component
GetJobber/atlantis pull request #367
Opened 2020-10-01 22:08 UTC by bdfranck

## Motivations

## Changes

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2020-10-02 17:13 UTC, bdfranck commented
My main uncertainty is how the drawer interacts with the layout of the parent element. Here are some options:

We could assume that the drawer is in a flex layout such as the following:

```
<div>
  <div>Main content</div>
  <Drawer title="A Drawer">
    Drawer content
  </Drawer>
</div>
```

Or we could have the drawer provide a wrapper for the main content such as the following:

```
<DrawerWrap>
  <div>Main content</div>
  <Drawer title="A Drawer">
    Drawer content
  </Drawer>
</div>
```

Or something else?

2020-10-19 22:06 UTC, bdfranck commented
Here's what's incomplete:

- This assumes we have access to a `<grid>` component like my proposal. I've added some inline CSS to the `mdx` file to show the effect.

Here's where I'm stuck:

- I'm not sure how to disable the page scrolling when the drawer fills the screen for mobile
- I'm not sure how to specify an external activator button to open the drawer

2020-10-26 15:36 UTC, eddysims commented
@seanhealy what are your thoughts on doing a drawer similar to the way we did `Toast`? This would mean that we don't need the `Page` or `Grid` component, as the drawer would be rendered at the end of the dom.

This would allow the drawer to be worked on right now as it would limit dependencies. However I'm not sure if this is a route that we want to go to often.

@bdfranck for reference. When we use the `Toast` component, we create a new small React App on the page that renders the Toast. This allows for it to be used multiple times on a page, or share a toast between React Apps without needing a `Provider`

2020-10-26 15:39 UTC, seanhealy commented
@eddysims I don't mind that idea. We would still need an anchor point for the drawer though as it does push the main content over when it opens.

2020-10-26 15:57 UTC, bdfranck commented
@eddysims That's interesting but it may be overkill for this. I chatted with @JeffMarvin last week and he identified two different types of drawers: an app-level one and a page-level one. The ML team only needs a page-level one at this point. Perhaps I could name it accordingly?

![image](https://user-images.githubusercontent.com/1479091/97196014-95637a80-1771-11eb-8e13-de13feafc6af.png)

2020-10-28 16:00 UTC, chris-at-jobber commented
@bdfranck we've fixed an issue causing specs to fail - if you update this branch from the latest master specs will pass ✅

2020-10-28 21:44 UTC, bdfranck commented
@chris-at-jobber Thanks for the advice! Is there a process to flag this PR as ready for an external review again?

2020-10-28 22:00 UTC, chris-at-jobber commented
I think if we flip the `review requested` label it will ping McWeb

2020-10-28 22:53 UTC, chris-at-jobber commented
I was wrong! Go to the "Reviewers" section, remove McWeb as a reviewer, and add McWeb back! (In the meantime, we are aware of this pending review 😄 )

![image](https://user-images.githubusercontent.com/39704901/97505199-140d1300-193e-11eb-8f47-b981cafc2c0e.png)

2020-11-05 15:58 UTC, bdfranck commented
@chris-at-jobber This is ready to review again! 🥳

2020-11-05 21:13 UTC, seanhealy requested changes
@bdfranck Looking good! Just had a couple little thoughts for you. Lemme know if you have any questions.

2020-11-05 21:13 UTC, seanhealy commented on packages/components/src/Drawer/Drawer.mdx
> +    const [modalOpen, setModalOpen] = useState(true);
`drawerOpen` may be better here.

2020-11-05 21:13 UTC, seanhealy commented on packages/components/src/Drawer/Drawer.test.tsx
> +it("renders a Drawer", () => {
Would probably be good to test that it doesn't render a drawer if `open` is false.

2020-11-05 21:13 UTC, seanhealy commented on packages/components/src/Drawer/Drawer.test.tsx
> +it("renders a Drawer", () => {
Also, if that `onRequestClose` is called when the `✖️` is clicked.

2020-11-05 21:13 UTC, seanhealy commented on packages/components/src/Drawer/Drawer.tsx
> +  onRequestClose?(): void;
I think we _may_ want to make this required as if they don't hook it up the `✖️` will do nothing when clicked.
```suggestion
  onRequestClose(): void;
```

2020-11-05 21:13 UTC, seanhealy commented on packages/components/src/Drawer/Drawer.tsx
> +function Header({ title, onRequestClose }: HeaderProps) {
Like that you split this out!

2020-11-06 16:27 UTC, bdfranck commented
### Cross-browser testing

#### Chrome (Latest)

- [ ] Displays properly on small breakpoint
- [ ] Displays properly on medium / large breakpoints
- [ ] Drawer toggles open and closed

#### Firefox (Latest)

- [ ] Displays properly on small breakpoint
- [ ] Displays properly on medium / large breakpoints
- [ ] Drawer toggles open and closed


#### Safari (Latest)

- [ ] Displays properly on small breakpoint
- [ ] Displays properly on medium / large breakpoints
- [ ] Drawer toggles open and closed


#### Edge (Latest)

- [ ] Displays properly on small breakpoint
- [ ] Displays properly on medium / large breakpoints
- [ ] Drawer toggles open and closed


#### Chrome on Android (Latest)

- [ ] Displays properly on small breakpoint
- [ ] Displays properly on medium / large breakpoints
- [ ] Drawer toggles open and closed


#### Safari on iOS (Latest)

- [ ] Displays properly on small breakpoint
- [ ] Displays properly on medium / large breakpoints
- [ ] Drawer toggles open and closed

2020-11-06 17:29 UTC, seanhealy requested changes
One last little rename and I think I'm happy!

2020-11-06 17:29 UTC, seanhealy commented on packages/components/src/Drawer/Drawer.mdx
> +    const [drawerOpen, setModalOpen] = useState(true);
```suggestion
    const [drawerOpen, setDrawerOpen] = useState(true);
```

2020-11-09 16:28 UTC, seanhealy approved these changes

2020-11-09 16:28 UTC, merged