feat(hooks): Adds useIsFirstRender hook
GetJobber/atlantis pull request #396
Opened 2020-10-23 08:52 UTC by 0length

### Overview 
This is refer to https://github.com/GetJobber/atlantis/pull/394#discussion_r509685744
### Changed

Create new hook called `useOnKeyDown` to create on keydown event listener handler by specific one or multyple key in the same function.
**Thanks**

2020-10-26 19:32 UTC, seanhealy requested changes
Looking great! Thanks so much. 😄 

Had a few little thoughts. Other than those it would be nice to have a test for this hook and I think we should be able to now use this hook [here so we don't have a duplicate](https://github.com/GetJobber/atlantis/blob/master/packages/components/src/Autocomplete/Menu.tsx#L160-L174).

2020-10-26 19:32 UTC, seanhealy commented on packages/hooks/src/useOnKeyDown/useOnKeyDown.mdx
> +    return (<Text>{text}<pre />{textTwo}</Text>);}}
Looks like we have an extra `<pre />` here.

2020-10-26 19:32 UTC, seanhealy commented on packages/hooks/src/useOnKeyDown/useOnKeyDown.mdx
> +    const letterText = "Delete me by pressing Delete key on your keyboard.";
Macs label backspace and delete quite oddly which make this example a bit confusing for users on that platform. We can probably get a way with simplifying this just down to a single example. How would you feel about removing this delete one and switching your second one to `escape` `space-enter` and something like `ctrl-i` or something?

2020-10-26 19:32 UTC, seanhealy commented on packages/hooks/src/useOnKeyDown/useOnKeyDown.mdx
> +    return (<Text>{text}<pre />{textTwo}</Text>);}}
Might also be nice to keep the instructions fixed and have a second line that displays the result of the key events.

2020-10-26 19:32 UTC, seanhealy commented on packages/hooks/src/useOnKeyDown/useOnKeyDown.mdx
> +`useOnKeyDown` should **only** only by used when making keyboard shortcut in any component.
Another little wording thought. 😄 

```suggestion
`useOnKeyDown` should **only ** be used when making keyboard shortcut in a component.
```

2020-10-26 19:32 UTC, seanhealy commented on packages/hooks/src/useOnKeyDown/useOnKeyDown.mdx
> +`useOnKeyDown` is an extremly simple hook that can be for adding the keydown event handler when the component is mounted and remove them when it unmount.
Little wording thought. 😄 

```suggestion
`useOnKeyDown` is a simple hook adding the keydown event handler when the component is mounted and removing when unmounted.
```

2020-10-26 19:32 UTC, seanhealy commented on packages/hooks/src/useOnKeyDown/useOnKeyDown.ts
> +  const handler: (event: globalThis.KeyboardEvent) => void = (
Our conventions would prefer this function defined with the `function` keyword.

```suggestion
function handler(event: globalThis.KeyboardEvent) {
```

2020-10-28 15:59 UTC, chris-at-jobber commented
@0length we've fixed an issue causing specs to fail - if you update this branch from the latest master specs will pass

2020-10-28 17:19 UTC, 0length commented
> @0length we've fixed an issue causing specs to fail - if you update this branch from the latest master specs will pass

Y

2020-10-28 17:21 UTC, 0length commented
> @0length we've fixed an issue causing specs to fail - if you update this branch from the latest master specs will pass

Yeah.. I have a problem with my leptop.. Maybe i will work the changes in 2-3day later.. And create with the test so..

2020-10-30 19:04 UTC, seanhealy commented
@0length Sorry to hear that your laptop is having a problem. Thanks so much for all your help during Hacktoberfest though! I'll mark this with the accepted label and we can sort the rest out later on. 😃

2020-12-10 21:58 UTC, chris-at-jobber commented
Closing - this got taken over the finish line in a [separate PR](https://github.com/GetJobber/atlantis/pull/432). Thanks for kicking this off @0length !

2020-12-10 21:58 UTC, closed without merging