feat(components): spinner loading state on input text
GetJobber/atlantis pull request #460
Opened 2021-01-28 18:21 UTC by linds14sr20det

## Motivations

This feature adds the ability to incorporate a spinner into the text input field. This would be used when a component is making a call to validate the contents of the field or doing some other long running task with the contents of the field.

## Changes

The spinner component now is used in the form field generic component.
### Added

- a boolean `showSpinner` has been added to the form field component, however it will only work with text input components.
### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

The mdx has a section that includes the spinner. 
---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2021-01-28 18:49 UTC, chris-at-jobber commented
Following the [guiding principles](https://atlantis.getjobber.com/CONTRIBUTING.md#guiding-principles) for Atlantis, I'd like to use a semantic name for this property.

Can we use a more meaningful `loading` similar to how we handle a similar feedback state on [Button](https://atlantis.getjobber.com/components/button#loading)?

2021-01-28 18:54 UTC, chris-at-jobber commented
I'd also be interested to see if there's an approach that allows us to make this change on `InputText` rather than `FormField`, if `InputText` is the only case for using this. It's a bit confusing that components like Select and Input Number now offer a `showSpinner` prop that doesn't do anything. 

This is a technical question which I don't have the answer to, but would make it more understandable on the other components if we can have this property only be present for the component that it's needed for.

2021-01-28 18:55 UTC, chris-at-jobber submitted a review, later dismissed
Property name should be more meaning-driven than presentation-driven; my other comment about where this change is applied is more open to discussion!

2021-01-28 21:38 UTC, linds14sr20det commented
@chris-at-jobber Agreed on the rename from showSpinner to loading. That's done and pushed up.

As for your second comment I'd like to put this on inputText only, but that isn't possible due to the way inputText is built. It renders a type of form field, and form field would need to be refactored to yield child content. We would also have to consider how yielding child content would affect all other formfield components. Basically it'd be a much bigger re-write than I'm willing to take on right now.

2021-01-28 22:47 UTC, linds14sr20det commented
@seanhealy @chris-at-jobber this should be good for review pending the design proposal. Unsure why the autocomplete snapshot wanted to be updated.

2021-01-28 22:50 UTC, chris-at-jobber commented
@linds14sr20det that Autocomplete snapshot is something we're trying to debug, you can kick it out and tests should get back to passing.

@seanhealy I think I have enough context from previous discussions about this with @JeffMarvin and @jlelford ; I'm not going to be available for reviews tomorrow, so consider this design approval on my end.

2021-01-29 17:48 UTC, seanhealy requested changes
Two little thoughts for you.

2021-01-29 17:48 UTC, seanhealy commented on packages/components/src/FormField/FormField.test.tsx
> +  expect(classNames).toContain("spinner small");
I think we can just check chat the result of `getByLabelText("loading")` is an instance of HTMLElement as the rest of this is checking concerns that are internal to the Spinner component.

2021-01-29 17:48 UTC, seanhealy commented on packages/components/src/FormField/FormField.tsx
> +        <span className={styles.icon}>
Are you ok changing this `icon` classname to `postfix` or something since that's what it's more shifted into here?

2021-01-29 21:23 UTC, seanhealy approved these changes

2021-01-29 21:24 UTC, merged