fix(components) : Export date formatting as a string
GetJobber/atlantis pull request #466
Opened 2021-02-04 21:52 UTC by Afroholic78

## Motivations
We needed to export formatDate as a string so the resulting date can be passed as an attribute to other components.
Allowing the returned formatted date to be a string offers more flexibility on the places it can be used.

## Changes
Exported the strFormateDate (the method used by FormatDate).

## Testing
I'm now able to import `strFormatDate` and use it.

---

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2021-02-04 21:52 UTC, Afroholic78 commented
Additionally to this PR, I wonder if we should be allowing a date formatting to passed in ?

2021-02-05 17:52 UTC, Afroholic78 commented
@seanhealy we had discussed this change a while back, you mind giving it a review. Let me know if you have thoughts on https://github.com/GetJobber/atlantis/pull/466#issuecomment-773627650

2021-02-08 17:06 UTC, eddysims commented
Hey, @Afroholic78 the code for this looks good. Now that the function is available through `@jobber/components`, I think that we should add some documentation into the `FormatDate` mdx files about it.

2021-02-08 20:20 UTC, Afroholic78 commented
@eddysims sounds good, 
I was wondering is there a reason we wouldn't want to use `moment` under the hood to allow the passing of specific date formats (instead of using the Date implementation)

2021-02-08 23:07 UTC, Afroholic78 commented
@eddysims Made the changes requested

2021-02-09 17:09 UTC, eddysims requested changes

2021-02-09 17:09 UTC, eddysims commented on packages/components/src/FormatDate/FormatDate.mdx
> +
Something happened here with the `frontmatter`

![image](https://user-images.githubusercontent.com/46460840/107400014-a0db7700-6abe-11eb-8a8e-2d6469b261f3.png)

2021-02-09 17:09 UTC, eddysims commented on packages/components/src/FormatDate/FormatDate.mdx
> +## Getting a string version
Can we add a description here of why someone would need a string version?

2021-02-09 19:07 UTC, Afroholic78 commented
@eddysims made the changes required
What about `date-fns`? https://www.npmjs.com/package/date-fns
I can drop it for now if it's a bigger conversation than is warranted for this PR. 
But because we need a specific format the current formatting solution won't really hold up. 😬

2021-02-10 17:26 UTC, eddysims approved these changes

2021-02-10 17:27 UTC, eddysims commented
@Afroholic78 yeah I think let's take that discussion out of this PR as adding new libraries should involve some discussion and investigation.

2021-02-10 17:29 UTC, merged