feat(docz-tools): TableOfContents component
GetJobber/atlantis pull request #471
Opened 2021-02-12 00:22 UTC by eddysims

## Motivations

## Changes

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2021-03-16 16:29 UTC, seanhealy commented on packages/docz-tools/components/DoczTOC/DoczTOC.tsx
> +          {headings.map((heading: Heading) => {
I had changed the TOC component in docs to use a filter instead so react doesn't have to render anything for excluded items. The current fragment strategy was giving me key warnings.

```tsx
        <ul className={styles.list}>
          {headings
            .filter((heading: Heading) => {
              return !(
                (maxDepth && heading.depth > maxDepth) ||
                (exclude && exclude.includes(heading.value)) ||
                (exclude && exclude.includes(heading.slug))
              );
            })
            .map((heading: Heading) => {
              const itemClassName = classNames(
                styles.link,
                styles[`l${heading.depth}`],
              );

              return (
                <li key={heading.slug} className={itemClassName}>
                  <a href={`#${heading.slug}`} className={styles.link}>
                    {heading.value}
                  </a>
                </li>
              );
            })}
        </ul>
```

2021-03-16 16:29 UTC, seanhealy requested changes
Thought about using filter

2021-03-18 20:42 UTC, eddysims commented
@seanhealy this one is ready for re-review

2021-03-19 15:58 UTC, seanhealy approved these changes

2021-03-19 15:58 UTC, merged