chore: update prettier in root and eslint package
GetJobber/atlantis pull request #476
Opened 2021-03-02 21:49 UTC by eddysims

## Motivations

Somewhere along the way prettier didn't like our `mdx`. It started to complain whenever an mdx file went through husky. 

This PR updates prettier to the latest version. This allows for fixing `mdx` files

## Changes

Updates Prettier

### Added

- 

### Changed

- Updates prettier

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2021-03-02 23:21 UTC, seanhealy requested changes
I think we had a change that cased prettier to add a bunch more parenthesis. I think it would be good to look a bit at what would have caused that. 😄

2021-03-02 23:21 UTC, seanhealy commented on ensureChangelogHeaders.js
> +glob.sync(path.join("packages/*/CHANGELOG.md")).forEach((file) => {
I wonder if there was a prettier config change that is adding all the extra parenthesis on cases like this.

2021-03-03 15:59 UTC, eddysims commented
@seanhealy looked at that and added in the prettier config to keep the params out.

2021-03-03 19:14 UTC, seanhealy approved these changes

2021-03-03 19:15 UTC, merged