docs(components): Add accessibility notes to Spinner
GetJobber/atlantis pull request #486
Opened 2021-03-15 17:49 UTC by chris-at-jobber

## Motivations

@rebecca-li asked a good question about accessibility relating to loading states and I didn't have any of our own documentation on this to share 😭 

## Changes

Added accessibility section to Spinner

### Added

- accessibility section to Spinner

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2021-03-16 15:49 UTC, seanhealy requested changes

2021-03-16 15:49 UTC, seanhealy commented on packages/components/src/Spinner/Spinner.mdx
> +<Props of={Spinner} />
Our other components have the props list immediately following the first example. For consistency I think it would be good to keep these there.

2021-03-16 22:25 UTC, chris-at-jobber commented
@seanhealy back to you! 🙏

2021-04-08 16:48 UTC, seanhealy approved these changes

2021-04-08 16:58 UTC, merged