docs: add installation notes to Atlantis home
GetJobber/atlantis pull request #511
Opened 2021-04-20 18:35 UTC by chris-at-jobber

## Motivations

Our installation instructions are buried pretty deep in our IA - using Atlantis should be a key piece of info for contributors!

## Changes

Added packages overview and links to installation

### Added

- Added packages overview and links to installation

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2021-04-21 15:48 UTC, eddysims requested changes

2021-04-21 15:48 UTC, eddysims commented on docs/README.md
> +Atlantis are installed and updated using [npm](https://www.npmjs.com/). This following list
```suggestion
Atlantis packages are installed and updated using [npm](https://www.npmjs.com/). This following list
```

2021-04-21 15:48 UTC, eddysims commented on docs/README.md
> +- [Components](https://atlantis.getjobber.com/packages/components#installation)
these links can be just `/packages/...`. This way they will work locally too

2021-04-21 15:48 UTC, eddysims commented on docs/README.md
> +- [Components](https://atlantis.getjobber.com/packages/components#installation)
I would also say lets link these to the page and not the `installation` heading, This way the reader will understand the package as well

2021-04-21 18:42 UTC, chris-at-jobber commented
@eddysims thanks! Back to you 🏓

2021-04-22 16:25 UTC, eddysims approved these changes

2021-04-22 16:25 UTC, merged