fix(docz-tools): Make Atlantis theme responsivise.
GetJobber/atlantis pull request #547
Opened 2021-05-13 20:28 UTC by eddysims

## Motivations

Atlantis is not very usable on a mobile device. This PR will make Atlantis work on a mobile device
 
## Changes

### Added

- 

### Changed

- Moved Layout component to use CSS modules
- Added responsive styles to Layout and Playground

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2021-05-13 20:39 UTC, chris-at-jobber commented on packages/docz-tools/src/gatsby-theme-docz/components/Layout/Layout.tsx
> +          <Button icon={open ? "remove" : "menu"} onClick={handleClick} />
can we make this a `tertiary` button?

2021-05-13 20:40 UTC, chris-at-jobber commented
@seanhealy can you take a look? Just the one comment from me

2021-05-13 20:41 UTC, chris-at-jobber requested changes
just changing the toggle button type and I'm good

2021-05-13 20:57 UTC, chris-at-jobber commented
A question, non-blocking: is it possible to have the menu close when tapping the overlay?

2021-05-13 23:56 UTC, chris-at-jobber commented on packages/docz-tools/src/gatsby-theme-docz/components/Layout/Layout.module.css
> +  background: var(--color-surface);
Another thought, also non-blocking... we should use a consistent color as with Menu and Modal (greyBlue at 80% opacity).

I was thinking as I did the color swaps in our components that I missed the opportunity to add a `color-overlay` variable, but looking at those components we actually implement in different ways. Menu uses an [rgba value](https://github.com/GetJobber/atlantis/blob/master/packages/components/src/Menu/Menu.css#L111) equivalent to greyBlue at 80%, while Modal uses [greyBlue and sets an opacity](https://github.com/GetJobber/atlantis/blob/master/packages/components/src/Modal/Modal.css#L29) on the element.

2021-05-17 15:23 UTC, eddysims commented
@chris-at-jobber I have addressed your comments.

Can you also take a look at `colors.css` and take a look at how I have approached the `--color-overlay`. I think that this is a good way to go with this, but would like your thoughts as well.

2021-05-17 15:59 UTC, chris-at-jobber commented on packages/design/src/colors.css
> +  --color--greyBlue--rgb: 101, 120, 132;
Ooooh this kind of blew my mind, I think this is good! I had to read it a few times before I realized _how_ it was working, but this is, I think, a good solution.

2021-05-17 16:01 UTC, chris-at-jobber approved these changes
Looks good to me! Might be good to have @seanhealy or @hosseintalebi take a look as well but this is a nice fix.

2021-05-17 19:57 UTC, merged