refactor(components): remove cancel from button and uses of button
GetJobber/atlantis pull request #651
Opened 2021-09-15 17:50 UTC by chris-at-jobber

## Motivations

We have removed all instances of `cancel` in uses of Atlantis button; this removes the cancel variation from Button itself 

## Changes

### Removed

- cancel, replaced with subtle

## Testing

- TODO: Automated tests failing on Modal

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2021-09-15 19:22 UTC, joelwarrington-jobber commented
@chris-at-jobber maybe this should be marked as a breaking change, so it triggers a major version bump

2021-09-21 20:20 UTC, joelwarrington-jobber requested changes
@chris-at-jobber can you merge latest master in to resolve conflicts?

Afterwards, should be okay to review, and likely approve!

2021-09-24 20:29 UTC, chris-at-jobber commented
@joelwarrington-jobber if you have some time this is ready for a look!

2021-09-24 20:30 UTC, chris-at-jobber commented on packages/components/src/Button/Button.mdx
> +        <Button label="Dismiss" type="secondary" variation="subtle" />
Showing a broader range of examples

2021-09-24 20:31 UTC, chris-at-jobber commented on packages/components/src/Button/Button.tsx
> +  XOR<DestructiveActionProps, SubmitActionProps>
I think this is appropriate use of XOR?

2021-09-24 20:46 UTC, joelwarrington-jobber approved these changes
LGTM

`cancel` variation no longer works and is replaced by `subtle`
![image](https://user-images.githubusercontent.com/80279872/134737496-8d445b91-3921-4c75-95d6-a145ee0a5bcd.png)
![image](https://user-images.githubusercontent.com/80279872/134737539-0b7f197f-5cdf-46e4-8a0f-cadde7c0e884.png)

ConfirmationModal working as expected:
![image](https://user-images.githubusercontent.com/80279872/134737747-263d286c-67d0-4d66-adce-44fa3181a223.png)


Have also confirmed locally that the Typing of Button is accurate to what we want.
- Error when trying to use `cancel`
- `type` restrictions on Submit type button

2021-11-30 01:44 UTC, adambobadam commented
LGTM, just wondering why `cancel` is beeing yeeted in the first place.  I.e., are there any instances where using `subtle` instead of `cancel` wouldn't make sense? Or where `cancel` might still be needed?

2021-11-30 18:06 UTC, chris-at-jobber commented
@adambobadam more details on the initial work [here!](https://jobber.atlassian.net/browse/JOB-34785)

2021-11-30 18:10 UTC, adambobadam commented
> @adambobadam more details on the initial work [here!](https://jobber.atlassian.net/browse/JOB-34785)

Thanks for that! 🙏

2021-11-30 22:08 UTC, chris-at-jobber commented
Also chatted offline w/ @adambobadam 

![image](https://user-images.githubusercontent.com/39704901/144135979-2f8a3480-801f-4f71-bd48-4ad3ed4db6d9.png)

2021-11-30 22:08 UTC, merged