docs: Add content guidelines to Banner component
GetJobber/atlantis pull request #722
Opened 2021-10-05 22:46 UTC by ChristyCampos

## Motivations

 Realized documentation guidelines for Banner were not available around how much content is appropriate for this component.

## Changes

 

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2021-10-05 23:01 UTC, chris-at-jobber requested changes
Small changes! This is looking good.

2021-10-05 23:01 UTC, chris-at-jobber commented on packages/components/src/Banner/Banner.mdx
> +<ul>
You can write this section in markdown and get rid of the HTML, like:

```
- Be concise and kept to only 1 to 2 sentences where possible
- Avoid exceeding 200 characters
- Follow the [product vocabulary](/content/product-vocabulary) where applicable
- In the case of warning or error banners, explain how to resolve the issue
```

2021-10-06 15:52 UTC, ChristyCampos commented on packages/components/src/Banner/Banner.mdx
> +  <li>Follow the product vocabulary guide where applicable</li>
@chris-at-jobber got 'er done.

2021-10-06 17:08 UTC, chris-at-jobber approved these changes

2021-10-06 17:08 UTC, merged