feat(design): update overlay color to black
GetJobber/atlantis pull request #861
Opened 2022-02-25 21:09 UTC by agglasaur

## Motivations

We'd like to replace our grey-blue overlay color as it very different than native mobile alert overlays which can be jarring particularly if they appear back-to-back. Also I can't remember what Josh said exactly, but the grey-blue looks off/dated.

## Changes

- Overlay color set to default Material overlay values

### Added

- Added black as a base color to use as a base for the overlay color.

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2022-02-25 23:23 UTC, chris-at-jobber commented on packages/components/src/LightBox/LightBox.css
>    opacity: 0.8;
I _think_ you need to lose this `opacity` value since the `color-overlay` handles the opacity internally.

2022-02-25 23:23 UTC, chris-at-jobber commented on packages/components/src/Modal/Modal.css
> +  background-color: var(--color-overlay);
Same comment as above

2022-02-25 23:50 UTC, chris-at-jobber commented
![image](https://user-images.githubusercontent.com/39704901/155818067-2cff6653-8ee3-4901-8931-a3fa23fab4b5.png)

[Menu](https://f322ac12.atlantis.pages.dev/components/menu) is still using an outdated overlay value on small screens:
![image](https://user-images.githubusercontent.com/39704901/155818096-9bcc2536-2bdc-411f-9f0f-00bb5f2afd71.png)

2022-02-25 23:52 UTC, chris-at-jobber commented
[FormatFile](https://f322ac12.atlantis.pages.dev/components/format-file) has a pseudo-element for overlaying uploads that this would be nice for
![image](https://user-images.githubusercontent.com/39704901/155818213-439d61a8-f954-431e-9607-44969c9abfc9.png)

2022-02-25 23:54 UTC, chris-at-jobber requested changes
Couple of components using "overlays" that should be standardized while we're in here

2022-02-28 17:58 UTC, agglasaur commented
Thanks @chris-at-jobber, excellent catches. Updates screenshots and ready for another review 🙏

2022-03-03 23:40 UTC, chris-at-jobber commented on packages/components/src/Menu/Menu.css
> -  ); /* until we figure out rgba + color vars... */
we figured it out 😭 😂

2022-03-03 23:41 UTC, chris-at-jobber approved these changes
Overlays have updated correctly!

2022-03-03 23:41 UTC, merged