refactor(design): Adjust banner alignment
GetJobber/atlantis pull request #989
Opened 2023-01-20 21:39 UTC by rodrigoeidelvein

## Motivations

## Changes

- Changed banner alignment

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

![Random photo of Atlantis](https://loremflickr.com/672/400/atlantis)

2023-01-20 21:46 UTC, chris-at-jobber commented on packages/components/src/Banner/Banner.css
> +  align-items: center;
@rodrigoeidelvein this breaks the alignment from what we expect / what was previously there

You can see this pushes the dismiss button to the center of the banner:
![image](https://user-images.githubusercontent.com/39704901/213810991-74894bfc-b383-4cfd-a2fc-f2533e60105a.png)

It should remain aligned to the top:
![image](https://user-images.githubusercontent.com/39704901/213811082-b2e6d17c-10b4-4831-b721-44fe8073c5f4.png)

2023-01-20 21:47 UTC, chris-at-jobber requested changes
Needs to solve the problem without breaking existing reflow behaviour

2023-01-23 17:29 UTC, chris-at-jobber commented
Wide looks good ✅ 
![image](https://user-images.githubusercontent.com/39704901/214107412-ef2d29fc-46c9-4944-ab01-e18422e8a23e.png)

Narrow looks good ✅ 
![image](https://user-images.githubusercontent.com/39704901/214107540-58261879-d728-4059-ba97-e7fa857ae083.png)
 
There's this intermediate break where I think the styling for a "narrow" banner is added, but the content is not long enough to wrap:
![image](https://user-images.githubusercontent.com/39704901/214107818-e93c931d-3e80-4ae6-9053-72689058bcd3.png)

I wouldn't call this a blocker since we already see this behaviour (see example), but wanted to flag it.
![image](https://user-images.githubusercontent.com/39704901/214108196-7c2ae5b4-300e-47a2-be00-bce4ca90622e.png)

2023-01-23 17:38 UTC, chris-at-jobber approved these changes
The changes look good to me. We'll definitely want to test this one "in the wild" with more complex usages, but this seems like a reasonable way to encapsulate the alignment into separate containers. It looks like you may have inadvertently also resolved an issue where custom child content could break!

### Before
Bullet list reflows on same line as paragraph, not good:
![image](https://user-images.githubusercontent.com/39704901/214110146-beff5218-552f-4951-93e5-570c45e6d165.png)

### After
Bullet list is beneath paragraph, as expected!
![image](https://user-images.githubusercontent.com/39704901/214110015-30892189-7aba-4602-81cf-133e940d13d6.png)

2023-01-23 17:46 UTC, rodrigoeidelvein commented
@chris-at-jobber that was all calculated 🤣

2023-01-23 18:31 UTC, merged